language: python
python:
- '3.6'
branches:
  only:
  - master
  - /^v.*$/
install:
- wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
- bash miniconda.sh -b -p $HOME/miniconda
- export PATH="$HOME/miniconda/bin:$PATH"
- hash -r
- conda config --set always_yes yes --set changeps1 no
- conda update -q conda
- conda info -a
- conda env create -f environment.yml
- source activate deepDegron
#- conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION numpy scipy nose pandas scikit-learn keras 
#- source activate test-environment
#- pip install pyensembl
#- pip install varcode
- pyensembl install --release 75 --species human --custom-mirror https://github.com/openvax/ensembl-data/releases/download/GRCh37.75/
- python setup.py install
script: nosetests --nologcapture tests/
