language: python
python:
- '3.6'
branches:
  only:
  - master
  - "/^v.*$/"
install:
- wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
- bash miniconda.sh -b -p $HOME/miniconda
- export PATH="$HOME/miniconda/bin:$PATH"
- hash -r
- conda config --set always_yes yes --set changeps1 no
- conda update -q conda
- conda info -a
- conda env create -f environment.yml
- source activate deepDegron
- pyensembl install --release 75 --species human --custom-mirror https://github.com/openvax/ensembl-data/releases/download/GRCh37.75/
- python setup.py install
- train_cterm_model --help
- train_nterm_model --help
- deepDegron_test --help
- deepDegron_score --help
script: nosetests --nocapture tests/
deploy:
  provider: pypi
  username: ctokheim
  password:
    secure: GRFZJesBjDDsCaPvf+uQ2NWTiFyCBJzRMatoS5hLkk2K5WlglcKwhvcZVSpUPbb2qPExo2RPZ/Gnu+2z0ZYm4E78s9RLnLsi5ymUEMVWFl8bLO1+mUPrcYk8lSBGgYDVlfUEEliBXESN8orej9/TM7eKRONVyixm9+JHHRS34TefKRRa5xrWtZ7lQc1dd0Sh1eGrrhNmF9ntyXQmUeRwhjOt71/+Lf5tyYDlF7wkxHV0Gi5EX5QTAUpFKrR/VxUPjDKCAhaL5NhO4mEDZ5Ufw7WpnccCJjtyIXXsZnlJe7nK7AQuSH4UPYGAPy4csxFzTluGeVjLDaIs97OmzcoLTljJigg3xEY3fiW3yxl2h4Xq8E4ZmNW0u72+6tfihbppxvTZN7LVx4AkGUDsJv9GbYQDRv1bPtmtUwveMJI081VEltg4vP37ZZ6OpkeYNgLEN57L+kgzFQ+5YtqeCjdGzLb047WwG5ewCvR4Qvt6fjmOp+Pz/OK69uXzZvKgF9rlwyjo440bmzmHq5WJjsGP/DHm7nmKi5nvvADFgk+2pTHhxKTVBDNGX4F1DJEjeRRWjfiqA93Qz8ml4vswmhDE1yDD7j5J8US2G9trGX2VuXpA025ONDGnAuKLZrAwd3hM2w2Xup/8Myv8TiOu7wukQuyq6OA+M5Pys/tSEKiJ2J0=
  on:
    tags: true
    branch: master
