language: python
python:
- '3.6'
branches:
  only:
  - master
  - "/^v.*$/"
install:
- wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
- bash miniconda.sh -b -p $HOME/miniconda
- export PATH="$HOME/miniconda/bin:$PATH"
- hash -r
- conda config --set always_yes yes --set changeps1 no
- conda update -q conda
- conda info -a
- conda env create -f environment.yml
- source activate deepDegron
- pyensembl install --release 75 --species human --custom-mirror https://github.com/openvax/ensembl-data/releases/download/GRCh37.75/
- python setup.py install
- train_cterm_model --help
- train_nterm_model --help
- deepDegron_test --help
- deepDegron_score --help
script: nosetests --nocapture tests/
deploy:
  provider: pypi
  username: ctokheim
  password:
    secure: k74RlCHycoM6aNFO2NxLfXCew0XLag8tcPx8MT3AsKStqN9ihorlvp1OeMK7POmKZJ4/NGZD/+X0lSFwOGf074Dm2lM9v0YIw7BObEKasTKhf5r/Pep/ULNuNWqr8q6aYph5AqOZT+NnBv9OfTYawxukGgbdBkDfZO47JknRkPsVHvbAxnvpPdu9a+FAVo/QCFVDt6BSNwXUuKCZNc+OGGTX9WRYuoI/DGZeNuJD4x0CuyCCgvpBIdGHdZBmgXmkoPdH5fE9h2zhLhmTWdJ+HKGy+0347omfMIfVgBoZwLYcnYyVow5awOhdwIqtZa2b9PD9Xrm204rSOtrhVeX3etWZlT6XAG60ShWSyqkLe/hvk6dTg/iEaO4A4h5YuowAzg6un6Dm4+CN0ZtQhU8il/m+c3hfhnbcJivnp+a6/ftCXyi4pL+cb3j2dT55BVpSTAl/9hAT7H5I8Dw93fNU+Cu9ORPP2b8qdAqARTBF2tw1kJ250B7r7C8pwkFOpSKFBcqddkhCCCMzbTbp2V9lMzs0f8G/5+wdVfqCtzncxiTUo39Hsabi8T3uaFKKVOLroH7WsrpM1v9zzRSRJsH2N0xjp2BwJhqno1lYTPji4gqrVYHVQl9wrLAR9vvptGedVqBuCv/cyi66FfUjwe2tCt0PZD3BqJ+M3maPw6rpWlo=
  on:
    tags: true
    branch: master
