name: deepDegron
channels:
- bioconda
- defaults
dependencies:
- pip
- setuptools<58
- numpy=1.16.5
- scipy 
- nose 
- pandas 
- scikit-learn 
- tensorflow=1.14.0
- keras
- pip:
  - pyensembl
  - varcode
